del absinterp\*.orig
del ag\*.orig
del algebra\*.orig
del automata\*.orig
del backend-tools\*.orig
del config\*.orig
del contain\*.orig
del csp\*.orig
del dataflow\*.orig
del dynparser\*.orig
del gc\*.orig
del generic\*.orig
del graph\*.orig
del graphtype\*.orig
del hash\*.orig
del html\*.orig
del machine\*.orig
del memory\*.orig
del numeric\*.orig
del objc\*.orig
del object\*.orig
del parser-tools\*.orig
del persist\*.orig
del pretty\*.orig
del prettypr\*.orig
del prop\*.orig
del rete\*.orig
del rewrite\*.orig
del scheduling\*.orig
del setl\*.orig
del sort\*.orig
del strings\*.orig
del symbolic\*.orig
del trees\*.orig
del tries\*.orig
del visualize\*.orig
